### ISSUE TITLE
NodeJS v4.0.0 Install fails on Windows

### ISSUE THREAD

**Issue by jakejackson1** [thecodingmachine/nodejs-installer#20]
Hi,

Just trying to get this composer package functioning correctly. My composer file has the following:

```
    "require-dev": {
        "mouf/nodejs-installer": "~1.0",
        "koala-framework/composer-extra-assets": "~1.1"
    },
```

And when I run `composer update` I get the following error:

```
Installing NodeJS v4.0.0
   Downloading from https://nodejs/org/dist/v4.0.0/node.exe
      Downloading: Connecting....

  [Composer\Downloader\TransportException]
  The "https://nodejs/org/dist/v4.0.0/node.exe" file could not be downloaded
   (HTTP/1.1 404 Not Found)
```

Any help would be appreciated.

**Comment by moufmouf** [comment]
Ok, with the new 4.0 version of Node, they suddenly changed the naming scheme of Windows URLs.
Just tag a new release that should fix this issue.

Let me know if you are encountering other problems.

**Comment by jakejackson1** [comment]
Awesome. Thanks for fixing the issue so quickly. Worked like a charm.
