### ISSUE TITLE
nodejs-installer fails on arm (continued)

### ISSUE THREAD

**Issue by Fabiensk** [thecodingmachine/nodejs-installer#28]
This is the continuation from #17 (nodejs-installer fails on arm (Raspberry pi). Installation failed on my Ubuntu for Odroid.

`> php -r 'print php_uname("m")."\n";'`
`armv7l`

Indeed the nodejs binaries for my architecture are available at https://nodejs.org/dist/v6.7.0/ under the name `node-v6.7.0-linux-armv7l.tar.gz`.

I could write a patch, but I don't know how to test it: I don't know how to make composer use the patched version of nodejs-installer on my machine.

Context: I try to install [Wallabag](https://www.wallabag.org/) on this machine.

**Comment by merwan** [comment]
Had the exact same issue while installing Wallabag on a [Scaleway C1 ARM server](https://www.scaleway.com/). I manually changed the line 171 in the `vendor/mouf/nodejs-installer/src/NodeJsInstaller.php` file in my Wallabag directory and added the missing `-linux` string and it installed correctly.
I will provide a patch ASAP.
