### ISSUE TITLE
Detection of local nodejs by priority

### ISSUE THREAD

**Issue by rodrigoaguilera** [thecodingmachine/nodejs-installer#31]
In my enviroment I have
`/usr/bin/node`
and
`/usr/local/bin/node`

The current code for this project search first for `/usr/bin/node` when I think it should give preference to `/usr/local/bin/node`

**Comment by moufmouf** [comment]
Hey @rodrigoaguilera ,

Interestingly enough, the code does not make any assumption about the directory NodeJS is installed in.

https://github.com/thecodingmachine/nodejs-installer/blob/1.0/src/NodeJsInstaller.php#L32-L52

As you can see, we simply try to find node in the PATH. So if your path is correctly set up, /usr/local/bin/node should be read before /user/bin/node.

The code however is looking for "nodejs" before "node". Maybe you have a /usr/bin/nodejs program and no /usr/local/bin/nodejs program on your computer? Might this be the source of your problem?

**Comment by rodrigoaguilera** [comment]
You are completely right.
I think it would too complicated to handle this case in this project. I'm closing if yo don't mind.

Thank you for investigating.
