### ISSUE TITLE
which output

### ISSUE THREAD

**Issue by nsams** [thecodingmachine/nodejs-installer#4]
With the newest version I'm getting the following output when running `composer install`:

```
which: no nodejs in (/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/android-sdk/platform-tools:/opt/android-sdk/tools:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/niko/.gem/ruby/2.1.0/bin:/home/niko/npm/bin:/home/niko/.gem/ruby/2.1.0/bin:/home/niko/npm/bin)
```

Doesn't cause any problems and can be ignored, but still looks like an error that might confuse people.

**Comment by moufmouf** [comment]
Hi Niko,

I'm taking a look but I don't seem to be able to reproduce the problem.
What OS are you testing on?

**Comment by nsams** [comment]
Linux. This simple test script shows the output:

```
<?php
shell_exec("which nodejs");
```
