### ISSUE TITLE
Update to work with Composer 2, needs upgrade to composer-plugin-api 2.0.0

### ISSUE THREAD

**Issue by ElijahLynn** [thecodingmachine/nodejs-installer#41]
See https://github.com/thecodingmachine/nodejs-installer/blob/1.0/composer.json#L17.

**Comment by moufmouf** [comment]
Indeed! I won't have time this week to work on the upgrade. However, if anyone is interested in opening a PR, I'll gladly accept it!

**Comment by ElijahLynn** [comment]
> Indeed! I won't have time this week to work on the upgrade. However, if anyone is interested in opening a PR, I'll gladly accept it!

Thanks, our team will have time to work on it in the coming weeks if there isn't a PR for it yet. I think it might be as simple as doing a `composer update composer-plugin-api` as I have seen some other libraries just change that and test it and it works.
