### ISSUE TITLE
Not work on Windows

### ISSUE THREAD

**Issue by Sogl** [thecodingmachine/nodejs-installer#5]
Hi!

I have a problem with wrapper script - it not works correctly on my WAMP:

```
C:\OpenServer\domains\aviashelf\vendor\koala-framework\kwf-modernizr>C:\OpenServer\domains\aviashelf/vendor/bin/npm install
"install" is not an internal or external
command, operable program or batch file.
```

Node.JS and NPM installed globally.

More info here:
https://github.com/koala-framework/koala-framework/issues/327

**Comment by nsams** [comment]
I can not reproduce with Windows 8.1, what do you use?

**Comment by Sogl** [comment]
Windows 8.1 x64

WAMP OpenServer:
http://open-server.ru

**Comment by Sogl** [comment]
Previous 1.0.1 worked well.

**Comment by nsams** [comment]
Ah, I can reproduce now, with node installed globally

**Comment by Sogl** [comment]
Good, I'm not alone =))

**Comment by moufmouf** [comment]
Damn, I can reproduce the problem too!
I'll take a deep look at it this afternoon.

**Comment by Sogl** [comment]
Thanks, now it works! =)

**Comment by Sogl** [comment]
Problem still exists on Windows:
https://github.com/vivid-planet/kwf-app-demo/issues/5

**Comment by nsams** [comment]
no, that is a different issue.
