### ISSUE TITLE
Remove NodeJS when removing package

### ISSUE THREAD

**Issue by ghost** [thecodingmachine/nodejs-installer#9]
Problem:

When removing the package, the locally installed NodeJS does not get removed.

Reproduce:

```
composer init
# configure "forceLocal": true
composer require --dev mouf/nodejs-installer
composer install --no-dev
```

Expected result:

vendor/nodejs folder should not be present.

Actual result:

vendor/nodejs folder exists.

**Comment by moufmouf** [comment]
True. I'll take a look at that.
